app = "channelsdvrnet-dns"

kill_signal = "SIGINT"
kill_timeout = 5

[metrics]
port = 9153
path = "/metrics"

[[services]]
  internal_port = 53
  protocol = "udp"

  [[services.ports]]
    port = 53

[[services]]
  internal_port = 53
  protocol = "tcp"

  [[services.ports]]
    port = 53
